services:

  database:
    image: mysql:8.4
    container_name: mysql_db
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: django_api
    env_file:
      - .env
      - ./backend/.env
    command: python manage.py runserver 0.0.0.0:${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src/app                       # live code
      - /usr/local/lib/python3.12/site-packages      # deps cache (anonymous)
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: next_ui
    env_file:
      - .env
      - ./frontend/.env
    ports:
      - "${HOST_PORT_FRONTEND}:3000"
    volumes:
      - ./frontend:/usr/src/app                      # live code
      - /usr/src/app/node_modules                    # deps cache
    depends_on:
      backend:
        condition: service_started

volumes:
  db_data: {}
