services:
  app:
    build: .
    container_name: app_dev
    command: npm run dev        # will echo & exit; swap for nodemon in real life
    ports:
      - "3000:3000"             # future-proof
    volumes:
      # 1️⃣ Live-reload source code
      - .:/usr/src/app:cached
      # 2️⃣ Anonymous volume for dependencies
      - app_node_modules:/usr/src/app/node_modules
      # 3️⃣ Anonymous volume for runtime data
      - app_data:/data

volumes:
  app_node_modules:
  app_data:
